In [1]:
%pip install nptyping beartype --upgrade --force

     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.2 kB 1.4 MB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 660.6 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 542.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/866.1 kB ? eta -:--:--
   - ------------------------------------- 30.7/866.1 kB 660.6 kB/s eta 0:00:02
   -- ------------------------------------ 61.4/866.1 kB 656.4 kB/s eta 0:00:02
   -- ------------------------------------ 61.4/866.1 kB 656.4 kB/s eta 0:00:02
   -- ------------------------------------ 61.4/866.1 kB 656.4 kB/s eta 0:00:02
   -- ------------------------------------ 61.4/866.1 kB 656.4 kB/s eta 0:00:02
   ----- -------------------------------- 122.9/866.1 kB 423.5 kB/s eta 0:00:02
   ----- -------------------------------- 122.9/866.1 kB 423.5 kB/s eta 0:00:02
   ----- -------------------------------- 122.9/866.1 kB 

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

a : np.ndarray = np.array(1000) # object to store

display(a) # prints
display(a.shape) # prints the shape of the object () = 0 -Denormalized
display(a.dtype) # prints the dtype of the object
display(type(a)) 
display(a.ndim) # prints the number of dimensions
display(a.size) # prints the size of the object
display(a.itemsize) # prints the itemsize of the object

array(1000)

()

dtype('int32')

numpy.ndarray

0

1

4

In [22]:
from nptyping import NDArray, Shape, UInt64
from typing import Any
data : NDArray[Shape["10"], Any] = np.arange(1,10)
display(data)
display(data.shape)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

(9,)

In [27]:
from nptyping import Bool

state_bank : NDArray[Shape["10"],Any] = np.array([1,7,8,10])
#[1,      7,      8,     10]
#[True,  False, False, True]
#variable[[True,  False, False, True]]
#[1,10]
select : NDArray[Shape["10"],Bool]= np.array([True, False, False, True])

state_bank[select]


array([ 1, 10])

In [30]:
state_bank : NDArray[Shape["10"],Any] = np.array([1,7,8,10])

ubl_bank : NDArray[Shape["100"],Any] = np.random.randint(1,100, 20)

display(state_bank)
display(ubl_bank)

array([ 1,  7,  8, 10])

array([28, 53,  6, 21, 51, 46, 50, 44, 95,  8,  8,  6, 84, 60, 19, 66,  9,
       65, 33,  2])

In [31]:
display(state_bank)
display(ubl_bank)

#        4item       search 20 items
np.in1d(state_bank,ubl_bank)

array([ 1,  7,  8, 10])

array([28, 53,  6, 21, 51, 46, 50, 44, 95,  8,  8,  6, 84, 60, 19, 66,  9,
       65, 33,  2])

array([False, False,  True, False])

In [32]:
display(state_bank)
display(ubl_bank)

#        4item       search 20 items
state_bank[np.in1d(state_bank,ubl_bank)]

array([ 1,  7,  8, 10])

array([28, 53,  6, 21, 51, 46, 50, 44, 95,  8,  8,  6, 84, 60, 19, 66,  9,
       65, 33,  2])

array([8])

In [1]:
pip install pandas

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB 640.0 kB/s eta 0:00:18
   ---------------------------------------- 0.0/11.5 MB 653.6 kB/s eta 0:00:18
   ---------------------------------------- 0.1/11.5 MB 653.6 kB/s eta 0:00:18
    --------------------------------------- 0.1/11.5 MB 944.1 kB/s eta 0:00:12
    --------------------------------------- 0.2/11.5 MB 1.1 MB/s eta 0:00:11
    --------------------------------------- 0.3/11.5 MB 1.1 MB/s eta 0:00:10
   - -------------------------------------- 0.4/11.5 MB 1.6 MB/s eta 0:00:08
   - -------------------------------------- 0.5/11.5 MB 1.7 MB/s eta 0:00:07
   - -------------------------------------- 0.6/11.5 MB 1.8 MB/s eta 0:00:07
   -- ------------------------------------- 0.8/11.5 MB 2.2 MB/s eta 0:00:05
   --- ------------------------------------ 1.1/11.5 MB 2.7 MB/s eta 0:00:04
   --- ------------------------------------ 1.1/11.5 MB 2.7 MB/s eta 0:00:0

In [2]:
pip install pandera

   ---------------------------------------- 0.0/209.0 kB ? eta -:--:--
   - -------------------------------------- 10.2/209.0 kB ? eta -:--:--
   ----- ---------------------------------- 30.7/209.0 kB 1.3 MB/s eta 0:00:01
   ----------- --------------------------- 61.4/209.0 kB 648.1 kB/s eta 0:00:01
   -------------------- ----------------- 112.6/209.0 kB 930.9 kB/s eta 0:00:01
   ----------------------------- -------- 163.8/209.0 kB 978.3 kB/s eta 0:00:01
   ---------------------------------------- 209.0/209.0 kB 1.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [6]:
import pandas as pd
import pandera as pa

# data to validate
df = pd.DataFrame({
    "column1": [1, 4, 0, 11, 9],
    "column2": [-1.3, -1.4, -2.9, -10.1, -20.4],
    "column3": ["value_1", "value_2", "value_3", "value_2", "value_1"],
})

# define schema
schema = pa.DataFrameSchema({
    "column1": pa.Column(int, checks=pa.Check.le(11)),
    "column2": pa.Column(float, checks=pa.Check.lt(-1.2)),
    "column3": pa.Column(str, checks=[
        pa.Check.str_startswith("value_"),
        # define custom checks as functions that take a series as input and
        # outputs a boolean or boolean Series
        pa.Check(lambda s: s.str.split("_", expand=True).shape[1] == 2)
    ]),
})

validated_df = schema(df)
print(validated_df)

   column1  column2  column3
0        1     -1.3  value_1
1        4     -1.4  value_2
2        0     -2.9  value_3
3       11    -10.1  value_2
4        9    -20.4  value_1


In [7]:
s1 : pd.Series = pd.Series([1,2,3,4,5], name="student id")
s2 : pd.Series = pd.Series([10,20,30,40,50], name="score")
s3 : pd.Series = pd.Series(["Hamza","Ali","Junaid","Rashid","Konain"], name="student name")


df1 : pd.DataFrame = pd.DataFrame({"student id":s1, "score":s2, "student name":s3})
df1

student id  score student name
0           1     10        Hamza
1           2     20          Ali
2           3     30       Junaid
3           4     40       Rashid
4           5     50       Konain

In [8]:
s1 : pd.Series = pd.Series([1,2,3,4,5], name="student id")
s2 : pd.Series = pd.Series([10,20,30,40,50], name="score")
s3 : pd.Series = pd.Series(["Hamza","Ali","Junaid","Rashid","Konain"], name="student name")


df1 : pd.DataFrame = pd.DataFrame([s1, s2, s3])
df1

0    1       2       3       4
student id        1    2       3       4       5
score            10   20      30      40      50
student name  Hamza  Ali  Junaid  Rashid  Konain

In [ ]:
dfl : list[pd.DataFrame] = pd.read_html('https://en.wikipedia.org/wiki/Minnesota')


In [21]:
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: '

In [71]:
import pandas as pd
import pandera as pa
import numpy as np
from nptyping import NDArray, Shape, Int64

total : int = 10000
s1 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(80, 100, (total,5))
ss1 : pd.DataFrame = pd.DataFrame(s1,columns=['s1','s2','s3','s4','s5'])

s2 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(70, 79,(total,5))
ss2 : pd.DataFrame = pd.DataFrame(s2,columns=['s1','s2','s3','s4','s5'])

s3 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(60, 69, (total,5))
ss3 : pd.DataFrame = pd.DataFrame(s3,columns=['s1','s2','s3','s4','s5'])

s4 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(50, 59, (total,5))
ss4 : pd.DataFrame = pd.DataFrame(s4,columns=['s1','s2','s3','s4','s5'])

s5 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(40, 49, (total,5))
ss5 : pd.DataFrame = pd.DataFrame(s5,columns=['s1','s2','s3','s4','s5'])

s6 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(33, 39, (total,5))
ss6 : pd.DataFrame = pd.DataFrame(s6,columns=['s1','s2','s3','s4','s5'])

s7 : NDArray[Shape[str(total)+"5"], Int64] = np.random.randint(0, 32, (total,5))
ss7 : pd.DataFrame = pd.DataFrame(s7,columns=['s1','s2','s3','s4','s5'])

s1  s2  s3  s4  s5
0    93  96  81  96  99
1    89  80  87  99  87
2    97  86  90  97  93
3    88  88  86  80  97
4    97  80  85  88  82
..   ..  ..  ..  ..  ..
995  93  80  98  83  91
996  97  83  80  85  88
997  83  81  84  95  86
998  96  80  90  88  95
999  95  89  81  96  91

[1000 rows x 5 columns]

In [40]:
df : pd.DataFrame = pd.concat([ss1,ss2,ss3,ss4,ss5,ss6,ss7]).reset_index(drop=True)

display(df.info())
print("================================================================")
display(df.describe())
print("================================================================")
display(df.head())# .head(n=60)
display("================================================================")
display(df.tail())

s1  s2  s3  s4  s5
69995  21   6   7  21  24
69996  12  25   9  29  29
69997  19  27   1  17  22
69998  30  12  20   1  26
69999  16  13  19  18  21

In [43]:
df.to_csv("student.csv", index=False)

In [45]:
df1 : pd.DataFrame = pd.read_csv("./student.csv")
df1.head()

s1  s2  s3  s4  s5
0  90  94  82  85  99
1  95  94  94  91  88
2  97  89  82  96  82
3  89  86  91  97  80
4  87  82  97  94  96

In [60]:
df1[0:10] # direct sicling apply on  rows index
df1.iloc[1:11 , 1:3] # numpy sicling apply on columns and rows index
df1.loc[1:11,"s1":"s3"] # direct sicling apply on columns and rows labels
df1.at[4,"s1"]
df1.iat[4,0]

87

In [64]:
def fn_obtained(s1: int, s2: int, s3: int, s4: int, s5: int)->int:
    return s1 + s2 + s3 + s4 + s5


df1['obtained'] = df1[["s1", "s2", "s3", "s4", "s5"]].apply(lambda x:fn_obtained(*x), axis=1)
df1

s1  s2  s3  s4  s5  obtained
0      90  94  82  85  99       450
1      95  94  94  91  88       462
2      97  89  82  96  82       446
3      89  86  91  97  80       443
4      87  82  97  94  96       456
...    ..  ..  ..  ..  ..       ...
69995  21   6   7  21  24        79
69996  12  25   9  29  29       104
69997  19  27   1  17  22        86
69998  30  12  20   1  26        89
69999  16  13  19  18  21        87

[70000 rows x 6 columns]

In [67]:
def fn_obtained(s1: int, s2: int, s3: int, s4: int, s5: int)->tuple[int, int,float, str]:
    total: int = 500
    obtained :int = s1 + s2 + s3 + s4 + s5
    per : float = obtained / total * 100
    grade : str = ""
    if per >= 80:
        grade =  "A+"
    elif per >= 70:
        grade = "A"
    elif per >= 60:
        grade = "B"
    elif per >= 50:
        grade = "C"
    elif per >= 40:
        grade = "D"
    elif per >= 33:
        grade = "E"
    else:
        grade = "F"
    return total, obtained, per, grade


df1[["Total",'obtained', 'percentage', "Grade"]] = df1[["s1", "s2", "s3", "s4", "s5"]].apply(lambda x:fn_obtained(*x), 
                                                                                             axis=1,
                                                                                             result_type='expand')
df1

s1  s2  s3  s4  s5  obtained  Total  percentage Grade
0      90  94  82  85  99       450    500        90.0    A+
1      95  94  94  91  88       462    500        92.4    A+
2      97  89  82  96  82       446    500        89.2    A+
3      89  86  91  97  80       443    500        88.6    A+
4      87  82  97  94  96       456    500        91.2    A+
...    ..  ..  ..  ..  ..       ...    ...         ...   ...
69995  21   6   7  21  24        79    500        15.8     F
69996  12  25   9  29  29       104    500        20.8     F
69997  19  27   1  17  22        86    500        17.2     F
69998  30  12  20   1  26        89    500        17.8     F
69999  16  13  19  18  21        87    500        17.4     F

[70000 rows x 9 columns]

In [69]:
from typing import Dict


remark : Dict[str,str] = {
    "A+" : "Excellent",
    "A" : "Very Good",
    "B" : "Good",
    "C" : "Fair",
    "D" : "Poor",
    "E" : "Very Poor",
    "F": "Fail"
}

df1['Remark'] = df1.Grade.map(remark)
df1

s1  s2  s3  s4  s5  obtained  Total  percentage Grade     Remark
0      90  94  82  85  99       450    500        90.0    A+  Excellent
1      95  94  94  91  88       462    500        92.4    A+  Excellent
2      97  89  82  96  82       446    500        89.2    A+  Excellent
3      89  86  91  97  80       443    500        88.6    A+  Excellent
4      87  82  97  94  96       456    500        91.2    A+  Excellent
...    ..  ..  ..  ..  ..       ...    ...         ...   ...        ...
69995  21   6   7  21  24        79    500        15.8     F       Fail
69996  12  25   9  29  29       104    500        20.8     F       Fail
69997  19  27   1  17  22        86    500        17.2     F       Fail
69998  30  12  20   1  26        89    500        17.8     F       Fail
69999  16  13  19  18  21        87    500        17.4     F       Fail

[70000 rows x 10 columns]

In [3]:
import pandas as pd
from datetime import datetime

# Define the data as a list of dictionaries with 10 student records
students_data = [
    {'roll_no': 1, 'name': 'Alice', 'father': 'Bob', 'course': 'Physics', 'date_of_admission': '2023-01-10', 'fee': 10000},
    {'roll_no': 2, 'name': 'Brian', 'father': 'Steve', 'course': 'Chemistry', 'date_of_admission': '2023-02-12', 'fee': 11000},
    {'roll_no': 3, 'name': 'Chloe', 'father': 'Tim', 'course': 'Biology', 'date_of_admission': '2023-03-14', 'fee': 12000},
    {'roll_no': 4, 'name': 'David', 'father': 'Rick', 'course': 'Mathematics', 'date_of_admission': '2023-04-10', 'fee': 13000},
    {'roll_no': 5, 'name': 'Eva', 'father': 'John', 'course': 'Computer Science', 'date_of_admission': '2023-05-16', 'fee': 14000},
    {'roll_no': 6, 'name': 'Frank', 'father': 'Tom', 'course': 'Economics', 'date_of_admission': '2023-06-21', 'fee': 15000},
    {'roll_no': 7, 'name': 'Grace', 'father': 'Harry', 'course': 'History', 'date_of_admission': '2023-07-25', 'fee': 16000},
    {'roll_no': 8, 'name': 'Henry', 'father': 'Charles', 'course': 'Geography', 'date_of_admission': '2023-08-17', 'fee': 17000},
    {'roll_no': 9, 'name': 'Isabel', 'father': 'Oliver', 'course': 'English', 'date_of_admission': '2023-09-10', 'fee': 18000},
    {'roll_no': 10, 'name': 'Jack', 'father': 'Noah', 'course': 'Art', 'date_of_admission': '2023-10-05', 'fee': 19000},
]

# Create the DataFrame
students_df : pd.DataFrame = pd.DataFrame(students_data)

# Convert 'date_of_admission' to datetime
students_df['date_of_admission'] = pd.to_datetime(students_df['date_of_admission'])

# Show the DataFrame
display(students_df)

# Verify the data types
display(students_df.info())


roll_no    name   father            course date_of_admission    fee
0        1   Alice      Bob           Physics        2023-01-10  10000
1        2   Brian    Steve         Chemistry        2023-02-12  11000
2        3   Chloe      Tim           Biology        2023-03-14  12000
3        4   David     Rick       Mathematics        2023-04-10  13000
4        5     Eva     John  Computer Science        2023-05-16  14000
5        6   Frank      Tom         Economics        2023-06-21  15000
6        7   Grace    Harry           History        2023-07-25  16000
7        8   Henry  Charles         Geography        2023-08-17  17000
8        9  Isabel   Oliver           English        2023-09-10  18000
9       10    Jack     Noah               Art        2023-10-05  19000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   roll_no            10 non-null     int64         
 1   name               10 non-null     object        
 2   father             10 non-null     object        
 3   course             10 non-null     object        
 4   date_of_admission  10 non-null     datetime64[ns]
 5   fee                10 non-null     int64         
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 612.0+ bytes


None

In [31]:
import pandera as pa
from pandera.typing import Series
from datetime import datetime
import pandas as pd

# Define the schema using SchemaModel
class StudentSchema(pa.SchemaModel):
    roll_no: Series[int] = pa.Field(ge=1)
    name: Series[str] = pa.Field(nullable=False)
    father: Series[str] = pa.Field(nullable=False)
    course: Series[str] = pa.Field(nullable=False)
    date_of_admission: Series[datetime] = pa.Field(le=datetime.now())
    fee: Series[int] = pa.Field(ge=0)

    class Config:
        coerce = True  # Automatically coerce types if possible
        strict = True  # Ensure all columns are accounted for in the schema

# Data for 10 students
students_data = [
    {'roll_no': 1, 'name': 'Alice', 'father': 'Bob', 'course': 'Physics', 'date_of_admission': '2023-01-10', 'fee': 10000},
    {'roll_no': 2, 'name': 'Brian', 'father': 'Steve', 'course': 'Chemistry', 'date_of_admission': '2023-02-12', 'fee': 11000},
    {'roll_no': 3, 'name': 'Chloe', 'father': 'Tim', 'course': 'Biology', 'date_of_admission': '2023-03-14', 'fee': 12000},
    {'roll_no': 4, 'name': 'David', 'father': 'Rick', 'course': 'Physics', 'date_of_admission': '2023-04-10', 'fee': 13000},
    {'roll_no': 5, 'name': 'Eva', 'father': 'John', 'course': 'Physics', 'date_of_admission': '2023-05-16', 'fee': 14000},
    {'roll_no': 6, 'name': 'Frank', 'father': 'Tom', 'course': 'Economics', 'date_of_admission': '2023-06-21', 'fee': 15000},
    {'roll_no': 7, 'name': 'Grace', 'father': 'Harry', 'course': 'History', 'date_of_admission': '2023-07-25', 'fee': 16000},
    {'roll_no': 8, 'name': 'Henry', 'father': 'Charles', 'course': 'Geography', 'date_of_admission': '2023-08-17', 'fee': 17000},
    {'roll_no': 9, 'name': 'Isabel', 'father': 'Oliver', 'course': 'English', 'date_of_admission': '2023-09-10', 'fee': 18000},
    {'roll_no': 10, 'name': 'Jack', 'father': 'Noah', 'course': 'Art', 'date_of_admission': '2023-10-05', 'fee': 19000},
]

# Create the DataFrame
students_df = pd.DataFrame(students_data)

# Convert 'date_of_admission' to datetime
students_df['date_of_admission'] = pd.to_datetime(students_df['date_of_admission'])

# Validate the DataFrame
validated_df = StudentSchema.validate(students_df)

print(validated_df)



   roll_no    name   father     course date_of_admission    fee
0        1   Alice      Bob    Physics        2023-01-10  10000
1        2   Brian    Steve  Chemistry        2023-02-12  11000
2        3   Chloe      Tim    Biology        2023-03-14  12000
3        4   David     Rick    Physics        2023-04-10  13000
4        5     Eva     John    Physics        2023-05-16  14000
5        6   Frank      Tom  Economics        2023-06-21  15000
6        7   Grace    Harry    History        2023-07-25  16000
7        8   Henry  Charles  Geography        2023-08-17  17000
8        9  Isabel   Oliver    English        2023-09-10  18000
9        9    Jack     Noah        Art        2023-10-05  19000


In [36]:
students_df.course.value_counts(dropna=False,normalize=True)

course
Physics      0.3
Chemistry    0.1
Biology      0.1
Economics    0.1
History      0.1
Geography    0.1
English      0.1
Art          0.1
Name: proportion, dtype: float64

In [37]:
students_df.course.value_counts(dropna=False,normalize=True)*100# also counts null cells values

course
Physics      30.0
Chemistry    10.0
Biology      10.0
Economics    10.0
History      10.0
Geography    10.0
English      10.0
Art          10.0
Name: proportion, dtype: float64

In [17]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Set a seed for reproducibility
np.random.seed(0)

# Define the number of transactions
num_transactions = 10

# Generate random dates within the current year
current_year = datetime.now().year
start_date = datetime(current_year, 1, 1)
end_date = datetime.now()

print(current_year,start_date,end_date)

# Generate a list of random dates within the year
random_dates = [start_date + timedelta(days=np.random.randint(0, (end_date - start_date).days))
                for _ in range(num_transactions)]

# Generate a list of random fee amounts
random_fees = np.random.randint(low=1, high=5000, size=num_transactions)

# Create the DataFrame
fee_transactions = pd.DataFrame({
    'date': random_dates,
    'fee': random_fees
})

# Sort by date for readability
fee_transactions.sort_values('date', inplace=True)

# Reset index after sorting
fee_transactions.reset_index(drop=True, inplace=True)

print(fee_transactions)


2024 2024-01-01 00:00:00 2024-02-08 03:44:24.815030
        date   fee
0 2024-01-01  3469
1 2024-01-04   706
2 2024-01-04  2600
3 2024-01-07  2894
4 2024-01-10  2136
5 2024-01-20  2223
6 2024-01-22  2898
7 2024-01-24   538
8 2024-01-25  2164
9 2024-02-06  1702


In [21]:
pd.cut(fee_transactions.fee, [1,1000,2000,3000,4000,5000]).value_counts(normalize=True)*100

fee
(2000, 3000]    60.0
(1, 1000]       20.0
(1000, 2000]    10.0
(3000, 4000]    10.0
(4000, 5000]     0.0
Name: proportion, dtype: float64

In [22]:

pd.qcut(fee_transactions.fee, [0,0.2,.4, .6, .8, 1]).value_counts(normalize=True)*100

fee
(537.999, 1502.8]    20.0
(1502.8, 2152.8]     20.0
(2152.8, 2373.8]     20.0
(2373.8, 2894.8]     20.0
(2894.8, 3469.0]     20.0
Name: proportion, dtype: float64

In [23]:
import pandera as pa
from pandera.typing import Series
from datetime import datetime
import pandas as pd

# Define the schema using SchemaModel
class StudentSchema(pa.SchemaModel):
    roll_no: Series[int] = pa.Field(ge=1)
    name: Series[str] = pa.Field(nullable=False)
    father: Series[str] = pa.Field(nullable=False)
    course: Series[str] = pa.Field(nullable=False)
    date_of_admission: Series[datetime] = pa.Field(le=datetime.now())
    fee: Series[int] = pa.Field(ge=0)

    class Config:
        coerce = True  # Automatically coerce types if possible
        strict = True  # Ensure all columns are accounted for in the schema

# Data for 10 students
students_data = [
    {'roll_no': 1, 'name': 'Alice', 'father': 'Bob', 'course': 'Physics', 'date_of_admission': '2023-01-10', 'fee': 10000},
    {'roll_no': 2, 'name': 'Brian', 'father': 'Steve', 'course': 'Chemistry', 'date_of_admission': '2023-02-12', 'fee': 11000},
    {'roll_no': 3, 'name': 'Chloe', 'father': 'Tim', 'course': 'Biology', 'date_of_admission': '2023-03-14', 'fee': 12000},
    {'roll_no': 4, 'name': 'David', 'father': 'Rick', 'course': 'physics', 'date_of_admission': '2023-04-10', 'fee': 13000},
    {'roll_no': 5, 'name': 'Eva', 'father': 'John', 'course': 'Physics', 'date_of_admission': '2023-05-16', 'fee': 14000},
    {'roll_no': 6, 'name': 'Frank', 'father': 'Tom', 'course': 'Economics', 'date_of_admission': '2023-06-21', 'fee': 15000},
    {'roll_no': 7, 'name': 'Grace', 'father': 'Harry', 'course': 'History', 'date_of_admission': '2023-07-25', 'fee': 16000},
    {'roll_no': 8, 'name': 'Henry', 'father': 'Charles', 'course': 'Geography', 'date_of_admission': '2023-08-17', 'fee': 17000},
    {'roll_no': 9, 'name': 'Isabel', 'father': 'Oliver', 'course': 'English', 'date_of_admission': '2023-09-10', 'fee': 18000},
    {'roll_no': 10, 'name': 'Jack', 'father': 'Noah', 'course': 'Art', 'date_of_admission': '2023-10-05', 'fee': 19000},
]

# Create the DataFrame
students_df = pd.DataFrame(students_data)

# Convert 'date_of_admission' to datetime
students_df['date_of_admission'] = pd.to_datetime(students_df['date_of_admission'])

# Validate the DataFrame
validated_df = StudentSchema.validate(students_df)

print(validated_df)



   roll_no    name   father     course date_of_admission    fee
0        1   Alice      Bob    Physics        2023-01-10  10000
1        2   Brian    Steve  Chemistry        2023-02-12  11000
2        3   Chloe      Tim    Biology        2023-03-14  12000
3        4   David     Rick    physics        2023-04-10  13000
4        5     Eva     John    Physics        2023-05-16  14000
5        6   Frank      Tom  Economics        2023-06-21  15000
6        7   Grace    Harry    History        2023-07-25  16000
7        8   Henry  Charles  Geography        2023-08-17  17000
8        9  Isabel   Oliver    English        2023-09-10  18000
9       10    Jack     Noah        Art        2023-10-05  19000


In [26]:
students_df['father']=='bob'.title()

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: father, dtype: bool

In [41]:
from datetime import datetime

date : datetime = datetime.now()
date

datetime.datetime(2024, 2, 8, 4, 11, 28, 363419)

In [42]:
s1 : pd.Series = pd.Series([date])
s1

0   2024-02-08 04:11:28.363419
dtype: datetime64[ns]

In [55]:
s1.dt.strftime("%Y/%m %d %I %b %B") 

0    2024/02 08 04 Feb February
dtype: object

In [57]:
import pandas as pd
from typing import Dict, Union, List, Iterator

from collections.abc import Iterator

# Sample data for the 'students' DataFrame
students_data : Dict[str,List[Union[str,int]]] = {
    'student_id': [1, 2, 3, 4, 5],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'teacher_id': [101, 102, 103, 101, 102]
}
students : pd.DataFrame = pd.DataFrame(students_data)

# Sample data for the 'teachers' DataFrame
teachers_data : Dict[str,List[Union[str,int]]] ={
    'teacher_id': [101, 102, 103],
    'course_name':['Physics', 'Chem','Maths'],
    'teacher_name': ['Mr. Smith', 'Ms. Johnson', 'Dr. Lee']
}
teachers = pd.DataFrame(teachers_data)

# Sample data for the 'student_fees' DataFrame
student_fees_data : Dict[str,List[Union[str,int]]] = {
    'student_id': [1, 2, 3, 4, 5],
    'fee_paid': [1500, 1500, 1500, 1500, 1500]
}
student_fees = pd.DataFrame(student_fees_data)
student_fees

student_id  fee_paid
0           1      1500
1           2      1500
2           3      1500
3           4      1500
4           5      1500